title: "[오늘 날짜] 회의록"
labels: [아침 짧은 회의를 통한 할일 정리와 현 상황 파악]
body:
  - type: text
    attributes:
      value: |
        🌟 **Daily Scrum Report** 🌟

  - type: textarea
    id: Done_Yesterday
    attributes:
      label: "✅ 1. 어제 한 일 (What we did yesterday)"
      value: "어제 진행한 업무를 정리하세요."

  - type: textarea
    id: Done_Yesterday_Kyunam
    attributes:
      label: "규남"
      value: "- 어제 수행한 작업을 입력하세요."

  - type: textarea
    id: Done_Yesterday_Yejin
    attributes:
      label: "예진"
      value: "- 어제 수행한 작업을 입력하세요."

  - type: textarea
    id: Done_Yesterday_Eunmi
    attributes:
      label: "은미"
      value: "- 어제 수행한 작업을 입력하세요."

  - type: textarea
    id: Plan_Today
    attributes:
      label: "📝 2. 오늘 할 일 (What I plan to do today)"
      value: "오늘 진행할 업무를 정리하세요."

  - type: checkboxes
    attributes:
      label: "규남"
      options:
        - label: "1번째 할 일"
        - label: "2번째 할 일"

  - type: checkboxes
    attributes:
      label: "예진"
      options:
        - label: "1번째 할 일"
        - label: "2번째 할 일"

  - type: checkboxes
    attributes:
      label: "은미"
      options:
        - label: "1번째 할 일"
        - label: "2번째 할 일"

  - type: textarea
    id: Help
    attributes:
      label: "❓ 3. 문제점 및 도움 요청 (Any blockers or help needed?)"
      value: "현재 겪고 있는 문제나 필요한 도움을 작성하세요."

  - type: textarea
    id: Links
    attributes:
      label: "🔗 4. 알게된 사실 및 
